- {name: Summary statistics, desc: "Automate mean, median, standard deviation, etc on measures", cat: Data Analytics}
- {name: Tableau Web Data Connector, desc: Host a custom data pipeline that integrates with Tableau, cat: Data Integration}
